Atividade.find_or_create_by(titulo: "Lavar Louça")
Atividade.find_or_create_by(titulo: "Jogar UNO")
Atividade.find_or_create_by(titulo: "Fazer Compras")
Atividade.find_or_create_by(titulo: "Planejar Curso")
Atividade.find_or_create_by(titulo: "Lavar o Banheiro")
Atividade.find_or_create_by(titulo: "Fazer Café")

Usuario.find_or_create_by(nome: "Fabio")
Usuario.find_or_create_by(nome: "Luis")
Usuario.find_or_create_by(nome: "Marco")
Usuario.find_or_create_by(nome: "Vinicius")
Usuario.find_or_create_by(nome: "Leonardo")
Usuario.find_or_create_by(nome: "Jeff")
