Atividade.create(titulo: "Lavar Louça")
Atividade.create(titulo: "Jogar UNO")
Atividade.create(titulo: "Fazer Compras")
Atividade.create(titulo: "Planejar Curso")
Atividade.create(titulo: "Lavar o Banheiro")
Atividade.create(titulo: "Fazer Café")
