require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MedalhasController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Medalha. As you add validations to Medalha, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MedalhasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all medalhas as @medalhas" do
      medalha = Medalha.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:medalhas)).to eq([medalha])
    end
  end

  describe "GET #show" do
    it "assigns the requested medalha as @medalha" do
      medalha = Medalha.create! valid_attributes
      get :show, params: {id: medalha.to_param}, session: valid_session
      expect(assigns(:medalha)).to eq(medalha)
    end
  end

  describe "GET #new" do
    it "assigns a new medalha as @medalha" do
      get :new, params: {}, session: valid_session
      expect(assigns(:medalha)).to be_a_new(Medalha)
    end
  end

  describe "GET #edit" do
    it "assigns the requested medalha as @medalha" do
      medalha = Medalha.create! valid_attributes
      get :edit, params: {id: medalha.to_param}, session: valid_session
      expect(assigns(:medalha)).to eq(medalha)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Medalha" do
        expect {
          post :create, params: {medalha: valid_attributes}, session: valid_session
        }.to change(Medalha, :count).by(1)
      end

      it "assigns a newly created medalha as @medalha" do
        post :create, params: {medalha: valid_attributes}, session: valid_session
        expect(assigns(:medalha)).to be_a(Medalha)
        expect(assigns(:medalha)).to be_persisted
      end

      it "redirects to the created medalha" do
        post :create, params: {medalha: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Medalha.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved medalha as @medalha" do
        post :create, params: {medalha: invalid_attributes}, session: valid_session
        expect(assigns(:medalha)).to be_a_new(Medalha)
      end

      it "re-renders the 'new' template" do
        post :create, params: {medalha: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested medalha" do
        medalha = Medalha.create! valid_attributes
        put :update, params: {id: medalha.to_param, medalha: new_attributes}, session: valid_session
        medalha.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested medalha as @medalha" do
        medalha = Medalha.create! valid_attributes
        put :update, params: {id: medalha.to_param, medalha: valid_attributes}, session: valid_session
        expect(assigns(:medalha)).to eq(medalha)
      end

      it "redirects to the medalha" do
        medalha = Medalha.create! valid_attributes
        put :update, params: {id: medalha.to_param, medalha: valid_attributes}, session: valid_session
        expect(response).to redirect_to(medalha)
      end
    end

    context "with invalid params" do
      it "assigns the medalha as @medalha" do
        medalha = Medalha.create! valid_attributes
        put :update, params: {id: medalha.to_param, medalha: invalid_attributes}, session: valid_session
        expect(assigns(:medalha)).to eq(medalha)
      end

      it "re-renders the 'edit' template" do
        medalha = Medalha.create! valid_attributes
        put :update, params: {id: medalha.to_param, medalha: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested medalha" do
      medalha = Medalha.create! valid_attributes
      expect {
        delete :destroy, params: {id: medalha.to_param}, session: valid_session
      }.to change(Medalha, :count).by(-1)
    end

    it "redirects to the medalhas list" do
      medalha = Medalha.create! valid_attributes
      delete :destroy, params: {id: medalha.to_param}, session: valid_session
      expect(response).to redirect_to(medalhas_url)
    end
  end

end
